name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: install
      run: |
        npm ci
        make package
        npm run install:tests

    - name: lint
      run: npm run lint

    - name: test
      run: npm test
      
    - name: upload unit coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.codecov_token }}
        file: ./coverage/lcov.info
        flags: unit
        name: unit tests
        fail_ci_if_error: true

    - name: upload mocha integration coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.codecov_token }}
        file: ./build/coverage/integration/javascript/mocha/lcov.info
        flags: integration, mocha, javascript
        name: mocha js integration tests
        fail_ci_if_error: true

    - name: upload jasmine integration coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.codecov_token }}
        file: ./build/coverage/integration/javascript/jasmine/lcov.info
        flags: integration, jasmine, javascript
        name: jasmine js integration tests
        fail_ci_if_error: true

    - name: upload manual coverage
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.codecov_token }}
        file: ./build/coverage/manual/lcov.info
        flags: manual, javascript
        name: manual tests
        fail_ci_if_error: true
